# Generated by Django 3.0.5 on 2020-10-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataperiodo',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
