# Generated by Django 3.0.5 on 2020-10-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201014_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='Agendado', max_length=15, verbose_name='Status'),
        ),
    ]
