# Generated by Django 3.0.5 on 2020-10-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201016_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='codigo_exibicao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código exibição'),
        ),
    ]
